name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Make help
      run: make help

    - name: Make about
      run: make about

    - name: Make copying
      run: make copying
      
    - name: get swagger file
      run: make _defs/swagger.json
